# Generated by Django 5.2.5 on 2025-08-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['restaurant', 'date'], name='api_menu_restaur_e745cf_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['employee', 'voted_at'], name='api_vote_employe_99f36a_idx'),
        ),
    ]
