# Generated by Django 5.2.5 on 2025-08-08 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_menu_api_menu_restaur_e745cf_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='menu',
            name='dishes',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.menu'),
        ),
    ]
